base_url = "https://th.org.pe"
title = "Rexmar"
default_language = "es"

compile_sass = true
generate_feeds = true
generate_sitemap = true
build_search_index = true

taxonomies = [
   { name = "tags", feed = false, render = true },
   { name = "categories", feed = false, render = true },
]

# ¡ESTA ES LA CLAVE! Le dice a Zola que use el formato compatible con Fuse.js
[search]
index_format = "fuse_json"

[extra]
description = "Rexmar - Agua de Mar Perú."
keywords = "agua de mar, rexmar, hipertonica, peru,  cobre, bienestar"

menu = [
    {url = "/", name = "Inicio"},
    {url = "/home/formas-de-uso-y-tips/", name = "Formas de Uso"},
    {url = "/home/recetas/", name = "Recetas"},
    {url = "/home/preguntas-frecuentes/", name = "Preguntas Frecuentes"},
    {url = "/rexcobre-artesanias/", name = "Rexcobre"},
    {url = "/distribuidores/", name = "Distribuidores"},
    {url = "/contacto/", name = "Contacto"},
]

[extra.author]
name = "legar"
email = "rexmaradm@gmail.com"

[extra.author.twitter]
link = "https://twitter.com/Rexmar_adm"
username = "Rexmar_adm"
