base_url = "https://rexmar.pages.dev"
title = "Rexmar"
default_language = "es"

compile_sass = true
generate_feeds = true
build_search_index = true

# ¡ESTA ES LA CLAVE! Le dice a Zola que use el formato compatible con Fuse.js
[search]
index_format = "fuse_json"

[extra]
description = "Rexmar - Agua de Mar Perú."
keywords = "agua de mar, cobre, bienestar"

menu = [
    {url = "/", name = "Inicio"},
    {url = "/home/formas-de-uso-y-tips/", name = "Formas de Uso"},
    {url = "/home/recetas/", name = "Recetas"},
    {url = "/home/preguntas-frecuentes/", name = "Preguntas Frecuentes"},
    {url = "/rexcobre-artesanias/", name = "Rexcobre"},
    {url = "/contacto/", name = "Contacto"},
]

[extra.author]
name = "Rexmar"
email = "rexmaradm@gmail.com"

[extra.author.twitter]
link = ""
username = ""
